# Functions II

## EOSC 211

**Week 8 Day 2**

**Learning Objectives:**  
1. Implement functions in your code
2. Understand the difference between a *fruitful* function (one that returns a variable) and void functions (one that performs an action but does not return anything

## Question 1

**We have two input arrays, `x` which is distance and `tpro` which is elevation in kilometers (say, along a survey line). Both have shape (99,). Use a *loop* and an *if statement* to write out a new variable `tlow` that contains only the values in `tpro` when the elevation is less than -1.8km.**

In [1]:
import numpy as np

x = np.linspace(0, 1000, 100)  # km along the survey line
tpro = 2 * np.sin(x)  # get some real topographical data here instead?

# your code here

In [2]:
# andrew's soln
tlow = np.array([])
for i in tpro:
    if i < 0.5:
        tlow = np.append(tlow,i)

print(tlow)

[ 0.         -1.25171757 -1.79396554  0.47456607 -1.58610056 -1.5329416
  0.39164486 -1.82988727 -1.18435776 -0.08491847 -1.96915287 -0.76812473
 -0.55663135 -1.99594266 -0.30801728 -0.99655007 -1.90872645  0.16968378
 -1.37954696 -1.71248592 -1.68374568 -1.41843012  0.22383416 -1.89177074
 -1.04335517 -0.25414305 -1.99173997 -0.60868495 -0.71760389 -1.97794324
 -0.13924733 -1.140076   -1.85116862  0.33814395 -1.49742824 -1.61865731
 -1.76924907 -1.29369012  0.05440936 -1.94001237 -0.8948288  -0.42153497
 -1.99996433 -0.44485586 -0.87340168 -1.94568058  0.03052675 -1.27538067
 -1.78026173 -1.60451135 -1.51315633  0.3616635  -1.84199414 -1.15962114
 -0.1154078  -1.97426428 -0.73984968 -0.58588713]


## Question 2

**Turn the code snippet above into a function that returns an array `tlow` that is exactly the same as Q1, but that takes as input (1) `tproin` and (2) a variable called `cutoff` that contains an arbitrary cut-off for the elevation  (ie, I might want to select elevations below -2km or -1.8 km or -1.5km, so make this a variable).**

**Finally, call your function with tpro as the input data and a cutoff of 1.8km**

In [3]:
# your code here

In [4]:
# andrew's soln
def select_elev(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    tlow = np.array([])
    for i in tpro:
        if i < cutoff:
            tlow = np.append(tlow, i)
    return tlow

select_elev(tpro, -1.8)

array([-1.82988727, -1.96915287, -1.99594266, -1.90872645, -1.89177074,
       -1.99173997, -1.97794324, -1.85116862, -1.94001237, -1.99996433,
       -1.94568058, -1.84199414, -1.97426428])

## Question 3

**Modify your function to return a *tuple* containing the elevations below `cutoff`, and the *indexes* of where those elements are found; ie `(tlow, tlow_ind)`.**

In [5]:
# your code here

In [6]:
# andrew's soln
def select_elev2(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    tlow = np.array([])
    tlow_ind = np.array([])
    for i in range(len(in_data)):
        if in_data[i] < cutoff: 
            tlow_ind = np.append(tlow_ind, i)
            tlow = np.append(tlow, in_data[i])
    return tlow, tlow_ind

low, ind = select_elev2(tpro, -1.5)
low, ind

(array([-1.79396554, -1.58610056, -1.5329416 , -1.82988727, -1.96915287,
        -1.99594266, -1.90872645, -1.71248592, -1.68374568, -1.89177074,
        -1.99173997, -1.97794324, -1.85116862, -1.61865731, -1.76924907,
        -1.94001237, -1.99996433, -1.94568058, -1.78026173, -1.60451135,
        -1.51315633, -1.84199414, -1.97426428]),
 array([ 3.,  6.,  8., 11., 16., 21., 26., 31., 34., 39., 44., 49., 54.,
        59., 62., 67., 72., 77., 82., 85., 87., 90., 95.]))

## Question 4

**Finally, I need not have used a loop and an “if” statement in the function.  How would I rewrite the body of the function in Exercise 2 to use logical indexing?  Note that the function call and function definition line don’t need to be changed.**

In [7]:
# your code here

In [8]:
# andrew's soln
def select_elev3(in_data, cutoff):
    """
    selects elements of a 1D np array in_data which are below the value cutoff.
    returns elements of in_data which are below cutoff
    """
    return in_data[in_data < cutoff]
    
select_elev3(tpro, -1.8)

array([-1.82988727, -1.96915287, -1.99594266, -1.90872645, -1.89177074,
       -1.99173997, -1.97794324, -1.85116862, -1.94001237, -1.99996433,
       -1.94568058, -1.84199414, -1.97426428])