# Data Structures II

## EOSC 211

**Week 3 Day 2**

**Learning Objectives:**  
1. Get more experience with Numpy arrays
2. Use built in functions to write efficient, *Pythonic* code

Useful references:

[Professor Kazarinoff](https://github.com/ProfessorKazarinoff/Problem-Solving-with-Python-37-Edition/blob/master/notebooks/05-NumPy-and-Arrays/05.03-Python-Lists-and-NumPy-Arrays.ipynb)

[Numpy Documentation](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [1]:
import numpy as np

## Question 1)

**A) Execute the following cells and describe IN WORDS what is happening in each cell**

In [2]:
lats=np.arange(1,21)
lats=np.arange(10,16)

In [3]:
L2 = np.array([lats[2], lats[4]])

In [4]:
L3 = np.array([lats[-1], lats[0]])

In [5]:
L4 = lats[lats > 13]

In [6]:
L5 = lats[lats >= 13]

In [7]:
L6 = lats[::-1]

In [8]:
L7 = lats[-1]
L7 = lats[4]
L7 = lats[len(lats)-1]

## Question 2

**A) We can change the shape of our `lats` array with numpy's built in funciton `reshape()`. What does the following code do?**

In [9]:
newlats = lats.reshape([2,3])

**B) What are all the possible shapes we can reassign to `lats`? Why do some work and others not**

your answer here

**C) We can return `lats` to it's original shape using `flatten()`, i.e.**

In [10]:
lats = newlats.flatten()
lats

array([10, 11, 12, 13, 14, 15])

**How else could you accomplish this? Write code in the following cell that outputs the same result starting with any of the `newlats` shapes we used above**

In [11]:
# your code here

In [12]:
# andrew's soln
lats = lats.reshape(len(lats))
lats

array([10, 11, 12, 13, 14, 15])

## Question 3

old question 3 from matlab version introduces OO data structure featuring a student 'joe lunchbucket', who's attributes include birthday and grade in EOSC211. Replace with different content and do talk about classes later?

## Question 4

**Along with `+`, `-`, `*`, `/`, python also defines the *floor division operator* `//` and the *modulo operator* `%`. Floor division (`//`) outputs the *quotient* of two integers, and modulo (`%`) outputs the remainder. Example code:**

In [13]:
5 // 2

2

In [14]:
5 % 2

1

**Write a few lines of code that will create the array `B`, which contains only the even valued elements of an array `A`. You don't know the size of `A` but you do know it contains only integers.**

In [15]:
# your code here

In [16]:
# andrew's soln
A = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
B = A[A % 2 == 0]
B

array([ 2,  4,  6,  8, 10])